MODEL_REPO=TheBloke/CodeLlama-7B-GGUF
MODEL_FILE=codellama-7b.Q4_K_M.gguf
MODEL_DISPLAY=CodeLlama
MODEL_PROVIDER=openai
MODEL_NAME=codellama-code
MODEL_API_BASE=http://localhost:8000/v1
CODE_TEMPERATURE=0.1
CODE_MAX_TOKENS=768
