# model-configs/openhermes.mk
export MODEL_REPO=TheBloke/OpenHermes-2.5-Mistral-7B-GGUF
export MODEL_FILE=openhermes-2.5-mistral-7b.Q4_K_M.gguf
export MODEL_DISPLAY=OpenHermes
export MODEL_PROVIDER=openai
export MODEL_NAME=openhermes-chat
export MODEL_API_BASE=http://localhost:8000/v1
export CHAT_TEMPERATURE=0.6
export CHAT_MAX_TOKENS=2048
export CODE_TEMPERATURE=0.2
export CODE_MAX_TOKENS=512
