MODEL_REPO=unsloth/Qwen3-8B-GGUF
MODEL_FILE=Qwen3-8B-Q4_K_M.gguf
MODEL_DISPLAY=Qwen3‑8B
MODEL_PROVIDER=openai
MODEL_NAME=qwen3-8b-code
MODEL_API_BASE=http://localhost:8000/v1
CODE_TEMPERATURE=0.2
CODE_MAX_TOKENS=512
