MODEL_REPO=TheBloke/zephyr-7B-alpha-GGUF
MODEL_FILE=zephyr-7b-alpha.Q4_K_M.gguf
MODEL_DISPLAY=Zephyr
MODEL_PROVIDER=openai
MODEL_NAME=zephyr-chat
MODEL_API_BASE=http://localhost:8000/v1
CHAT_TEMPERATURE=0.65
CHAT_MAX_TOKENS=2048
